import { useEffect, useMemo, useState } from "react";
type District={id:string;code:string;name:string;province:string;pouPct:number|null;undernourishedPeople:number|null;severityRank:number|null;scaleRank:number|null;persistenceSeverity?:number|null};
type Feature={properties:{code:string};geometry:{type:string;coordinates:unknown}};
type Hover={district:District;x:number;y:number}|null;
const project=([x,y]:number[])=>[(x-94)*18,(6-y)*23];
const rings=(g:Feature["geometry"])=>g.type==="Polygon"?[g.coordinates as number[][][]]:g.coordinates as number[][][][];
const makePath=(g:Feature["geometry"])=>rings(g).map(p=>p.map(r=>`M${r.map(c=>project(c).map(n=>n.toFixed(1)).join(",")).join("L")}Z`).join("")).join("");
const coords=(v:unknown,out:number[][]=[])=>{if(Array.isArray(v)&&typeof v[0]==="number")out.push(v as number[]);else if(Array.isArray(v))v.forEach(x=>coords(x,out));return out};
export function IndonesiaMap({districts,lens,selected,onSelect,portfolio,province}:{districts:District[];lens:"severity"|"scale"|"persistent";selected?:string;onSelect:(id:string)=>void;portfolio?:Set<string>;province?:string}){
 const[features,setFeatures]=useState<Feature[]>([]),[hover,setHover]=useState<Hover>(null),[zoom,setZoom]=useState(1);
 useEffect(()=>{fetch("/indonesia_kabkota.geojson").then(r=>r.json()).then(g=>setFeatures(g.features))},[]);
 const byCode=useMemo(()=>new Map(districts.map(d=>[d.code,d])),[districts]);
 const vals=districts.map(d=>lens==="severity"?d.pouPct:lens==="scale"?d.undernourishedPeople:d.persistenceSeverity).filter((v):v is number=>v!==null&&v!==undefined),max=Math.max(...vals),min=Math.min(...vals);
 const chosen=features.find(f=>byCode.get(f.properties.code.replace(".",""))?.id===selected);
 const viewBox=useMemo(()=>{if(!chosen||zoom===1)return"0 0 850 430";const ps=coords(chosen.geometry.coordinates).map(project),xs=ps.map(p=>p[0]),ys=ps.map(p=>p[1]),x=(Math.min(...xs)+Math.max(...xs))/2,y=(Math.min(...ys)+Math.max(...ys))/2,w=850/zoom,h=430/zoom;return`${x-w/2} ${y-h/2} ${w} ${h}`},[chosen,zoom]);
 const fill=(d?:District)=>{if(!d||d.pouPct===null)return"#d7dce0";if(portfolio)return portfolio.has(d.id)?"#3f6f4e":"#e7eaec";const v=lens==="severity"?d.pouPct:lens==="scale"?d.undernourishedPeople!:d.persistenceSeverity??0,t=(v-min)/(max-min||1);return`rgb(${Math.round(229-154*t)},${Math.round(235-104*t)},${Math.round(225-142*t)})`};
 return <div className="map-shell"><div className="map-toolbar"><button onClick={()=>setZoom(z=>Math.min(7,z+1))}>+</button><button onClick={()=>setZoom(z=>Math.max(1,z-1))}>−</button><button onClick={()=>setZoom(1)}>Reset</button></div><div className="map-legend"><strong>{lens==="severity"?"PoU (%)":lens==="scale"?"Affected population":"Top-15 years"}</strong><span>Low</span><i></i><span>High</span><span className="nodata">■ No data</span></div>{hover&&<div className="map-tooltip" style={{left:hover.x,top:hover.y}}><strong>{hover.district.name}</strong><span>{hover.district.province}</span><b>{lens==="severity"?`${hover.district.pouPct?.toFixed(2)}% PoU`:`${hover.district.undernourishedPeople?.toLocaleString()} affected`}</b><small>Severity #{hover.district.severityRank} · Reach #{hover.district.scaleRank}</small></div>}<svg className="indo-map" viewBox={viewBox} role="img" aria-label="Interactive Indonesia district priority map">{features.map(f=>{const d=byCode.get(f.properties.code.replace(".","")),dim=province&&province!=="All provinces"&&d?.province!==province;return <path tabIndex={d?0:-1} key={f.properties.code} d={makePath(f.geometry)} fill={fill(d)} opacity={dim?.2:1} className={selected===d?.id?"map-selected":""} onMouseMove={e=>d&&setHover({district:d,x:e.nativeEvent.offsetX+14,y:e.nativeEvent.offsetY+14})} onMouseLeave={()=>setHover(null)} onClick={()=>{if(d){onSelect(d.id);setZoom(4)}}} onKeyDown={e=>{if(d&&(e.key==="Enter"||e.key===" ")){onSelect(d.id);setZoom(4)}}}/>})}</svg></div>
}
